### ISSUE TITLE
No Settings in 10.0.2

### ISSUE THREAD

**Issue by cortho** [owncloud/guests#95]
In 10.0.2 the guests app settings are not accessible any more.

Reason:
`{
  "reqId":"7w881XEgG1qlYpAsO3s1",
  "level":3,
  "time":"2017-06-13T07:58:46+00:00",
  "remoteAddr":"172.17.0.1",
  "user":"admin",
  "app":"no app in context",
  "method":"GET",
  "url":"\/index.php\/settings\/personal",
  "message":"Section id not found: \"guests\". Apps should register settings sections in info.xml"
}`

**Comment by PVince81** [comment]
@cortho which version of the guests app ?

@IljaN @sharidas I believe this has been fixed already in the latest version, not sure if it was published yet

**Comment by sharidas** [comment]
I am able to see the setting in master branch of guest app with master branch of core: https://pasteboard.co/1Iwx9gHNa.png

**Comment by cortho** [comment]
I was using 0.4.1 from the marketplace

**Comment by pmaier1** [comment]
Fixed in https://github.com/owncloud/guests/pull/108. New release for marketplace is planned for next week.

**Comment by svengit** [comment]
Still no new version in marketplace or am I missing something?

**Comment by cortho** [comment]
@svengit The new version is in progress to being released, you may check https://github.com/owncloud/guests/issues/128 for the current status.

In case you are in urgent need, there is a small fix with which you can patch your current version, see https://github.com/owncloud/guests/pull/108/commits/dee57e053a0d399319014751b7f0d09d82c1f849#diff-7ce542aade9c380d3b2e16162d559256L47

**Comment by svengit** [comment]
Thanks for your answer. That fix seems to be a diff for a different version. The current version from the marketplace has 'guest' and not 'authentication'. Anyway, after changing it it still does not work and I get those nasty signature errors, so I'll just wait till the next version is life.

Thanks!

**Comment by pmaier1** [comment]
The release containing this fix, amongst others, will go live this week!
